#!/usr/bin/env python
# -*- coding: utf-8 -*-




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode
from bottle import html_escape

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.3.3'
__CHEETAH_versionTuple__ = (3, 3, 3, 'final', 0)
__CHEETAH_genTime__ = 1704324466.0275428
__CHEETAH_genTimestamp__ = 'Thu Jan  4 02:27:46 2024'
__CHEETAH_src__ = 'search_authors_form.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Jan  4 02:27:39 2024'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class search_authors_form(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(search_authors_form, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def search_type_checked(self, value, **KWS):



        ## CHEETAH: generated from #def $search_type_checked($value) at line 3, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if VFFSL(SL,"getVar",False)('search_type', '') == VFFSL(SL,"value",True): # generated from line 4, col 1
            write('''checked''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def case_sensitive_checked(self, **KWS):



        ## CHEETAH: generated from #def $case_sensitive_checked at line 8, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if VFFSL(SL,"getVar",False)('case_sensitive', None): # generated from line 9, col 1
            write('''checked''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<form action="/search_authors/" method="POST">
  <div style="width: 100%">
  <input name="search_authors" value="''')
        _v = VFFSL(SL,"html_escape",False)(VFFSL(SL,"getVar",False)('search_authors',
  ''))
        if _v is not None: write(_filter(_v, rawExpr="$html_escape($getVar('search_authors',\n  ''))")) # from line 15, col 39.
        write('''" type="text" style="width: 100%">
  <br>
  <input name="search_type" value="start" ''')
        _v = VFFSL(SL,"search_type_checked",False)('start') # "$search_type_checked('start')" on line 18, col 43
        if _v is not None: write(_filter(_v, rawExpr="$search_type_checked('start')")) # from line 18, col 43.
        write(''' type="radio">
  Подстрока в начале
  <input name="search_type" value="substring" ''')
        _v = VFFSL(SL,"search_type_checked",False)('substring') # "$search_type_checked('substring')" on line 20, col 47
        if _v is not None: write(_filter(_v, rawExpr="$search_type_checked('substring')")) # from line 20, col 47.
        write(''' type="radio">
  Подстрока
  <input name="search_type" value="full" ''')
        _v = VFFSL(SL,"search_type_checked",False)('full') # "$search_type_checked('full')" on line 22, col 42
        if _v is not None: write(_filter(_v, rawExpr="$search_type_checked('full')")) # from line 22, col 42.
        write(''' type="radio">
  Точное совпадение
  <br>
  <input name="case_sensitive" type="checkbox" ''')
        _v = VFFSL(SL,"case_sensitive_checked",True) # '$case_sensitive_checked' on line 25, col 48
        if _v is not None: write(_filter(_v, rawExpr='$case_sensitive_checked')) # from line 25, col 48.
        write('''>
  Различать прописные/строчные
  </div>
  <div style="width: 100%; text-align: center">
  <input name="submit" type="submit" value="Искать авторов">
  </div>
</form>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_search_authors_form = 'respond'

## END CLASS DEFINITION

if not hasattr(search_authors_form, '_initCheetahAttributes'):
    templateAPIClass = getattr(search_authors_form,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(search_authors_form)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=search_authors_form()).run()


