#! /bin/sh

cd "`dirname \"$0\"`"/.. &&
umask 022 &&
chmod -R a+rX . &&
set-commit-date.py &&

python setup.py build_py &&
python setup.py build --executable '/usr/bin/env python' &&
python setup.py sdist &&

for py in 2.7 3.4 3.5 3.6 3.7; do
   find build -name '*.py[co]' -delete &&
   python$py setup.py build_py &&
   python$py setup.py build --executable '/usr/bin/env python' &&
   python$py    -m compileall build &&
   python$py -O -m compileall build &&
   python$py setup.py bdist_egg || exit 1
done

find build -name '*.py[co]' -delete &&
python setup.py bdist_wheel --universal &&

twine upload dist/* &&
exec rm -rf build dist m_librarian.egg-info
