#! /bin/sh

cd "`dirname $0`"/.. &&
sphinx-apidoc --separate --module-first --suffix=rst --force \
   --output-dir=docs/api m_librarian &&
cd docs/api &&
exec rm m_librarian.web.views.rst m_librarian.web.views.*.rst
