name: Run tests

on: [push, pull_request]

jobs:
  run-tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
        include:
        - os: ubuntu-latest
          os-name: Linux
          pip-cache-path: ~/.cache/pip
        - os: macos-latest
          os-name: OSX
          pip-cache-path: ~/Library/Caches/pip
        - os: windows-latest
          os-name: w32
          pip-cache-path: ~\AppData\Local\pip\Cache

    name: Python ${{ matrix.python-version }} @ ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps:

      # Setup Python/pip
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ matrix.pip-cache-path }}
          key: ${{ runner.os }}-pip

      # Setup tox
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          pip --version
          pip install --upgrade virtualenv tox
      - name: Set TOXENV
        run: |
          import os, sys
          pyver = '%d%d' % tuple(sys.version_info[:2])
          toxenv = 'py%s-sqlite' % pyver
          if os.name == 'posix':
            toxenv += ',py%s-flake8' % pyver
          elif os.name == 'nt':
            toxenv += '-w32'
          with open(os.environ['GITHUB_ENV'], 'a') as f:
            f.write('TOXENV=' + toxenv + '\n')
        shell: python

      - name: Run tox
        run: |
          python -c "import os; print(os.environ['TOXENV'])"
          tox --version
          tox
