name: Run tests

on: [push, pull_request]

jobs:
  run-tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        include:
        - os: ubuntu-latest
          os-name: Linux
          pip-cache-path: ~/.cache/pip
        - os: macos-latest
          os-name: OSX
          pip-cache-path: ~/Library/Caches/pip
        - os: windows-latest
          os-name: w32
          pip-cache-path: ~\AppData\Local\pip\Cache

    name: Python ${{ matrix.python-version }} @ ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip-cache-path }}
          key: ${{ runner.os }}-pip
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade "pip<21.0" "setuptools<45" wheel
          pip --version
          python -m pip --version
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: Run tox targets for ${{ matrix.python-version }}
        run: python -m tox
